In [1]:
import torch
x_train = torch.FloatTensor([[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5],[1,2,5,6],[1,6,6,6],[1,7,7,7]])
y_train = torch.FloatTensor([[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]])

In [2]:
w = torch.randn(4,3,requires_grad=True)
b = torch.randn(1,3,requires_grad=True)
optimizer = torch.optim.Adam([w,b],lr=0.1)

In [3]:
for epoch in range(3001):
  h = torch.softmax(torch.mm(x_train, w)+b, dim=1)
  cost = -torch.mean(torch.sum(y_train*torch.log(h),dim=1))
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()
  with torch.no_grad():
    if epoch % 300 == 0:
      print("epoch: {}, cost: {:.6f}".format(epoch, cost.item()))

epoch: 0, cost: 7.539644
epoch: 300, cost: 0.199725
epoch: 600, cost: 0.094651
epoch: 900, cost: 0.054200
epoch: 1200, cost: 0.034679
epoch: 1500, cost: 0.023858
epoch: 1800, cost: 0.017257
epoch: 2100, cost: 0.012941
epoch: 2400, cost: 0.009969
epoch: 2700, cost: 0.007838
epoch: 3000, cost: 0.006262


In [5]:
x_test = torch.FloatTensor([[1,11,10,9],[1,3,4,3],[1,1,0,1]])
h_test = torch.softmax(torch.mm(x_test, w)+b, dim=1)
print(h_test)

tensor([[1.0000e+00, 2.0359e-16, 4.9599e-33],
        [6.7932e-04, 6.9867e-01, 3.0066e-01],
        [2.4414e-29, 2.5035e-10, 1.0000e+00]], grad_fn=<SoftmaxBackward0>)


In [ ]:
w.requires_grad_(False)
b.requires_grad_(False)
x_test = torch.FloatTensor([[1,11,10,9],[1,3,4,3],[1,1,0,1]])
test_all = torch.softmax(torch.mm(x_test, w)+b, dim=1)
print(test_all)
print(torch.argmax(test_all, dim=1))

tensor([[1.0000e+00, 1.2777e-15, 2.6541e-32],
        [4.8766e-03, 7.3287e-01, 2.6225e-01],
        [2.5874e-28, 2.3760e-10, 1.0000e+00]])
tensor([0, 1, 2])


In [14]:
import torch
import torch.nn.functional as F
x_train = torch.tensor([[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5],[1,2,5,6],[1,6,6,6],[1,7,7,7]],dtype=torch.float)
y_train = torch.tensor([2,2,2,1,1,1,0,0],dtype=torch.long)
w = torch.randn(4,3,requires_grad=True)
b = torch.randn(1,3,requires_grad=True)
optimizer = torch.optim.Adam([w,b],lr=0.1)
for epoch in range(3001):
  h = torch.mm(x_train,w) + b
  cost = F.cross_entropy(h, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  with torch.no_grad():
    if epoch % 300 == 0:
      print("epoch: {}, cost: {:.6f}".format(epoch, cost.item()))


epoch: 0, cost: 3.876289
epoch: 300, cost: 0.152500
epoch: 600, cost: 0.069838
epoch: 900, cost: 0.039837
epoch: 1200, cost: 0.025555
epoch: 1500, cost: 0.017645
epoch: 1800, cost: 0.012806
epoch: 2100, cost: 0.009631
epoch: 2400, cost: 0.007437
epoch: 2700, cost: 0.005859
epoch: 3000, cost: 0.004689


In [15]:
import torch
import torch.nn as nn
import torch.nn.functional as F
x_train = torch.tensor([[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5],[1,2,5,6],[1,6,6,6],[1,7,7,7]],dtype=torch.float)
y_train = torch.tensor([2,2,2,1,1,1,0,0],dtype=torch.long)
# w = torch.randn(4,3,requires_grad=True)
# b = torch.randn(1,3,requires_grad=True)
model = nn.Linear(4,3)
optimizer = torch.optim.Adam(model.parameters(),lr=0.1)
for epoch in range(3001):
  # h = torch.mm(x_train,w) + b
  h = model(x_train)
  cost = F.cross_entropy(h, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  with torch.no_grad():
    if epoch % 300 == 0:
      print("epoch: {}, cost: {:.6f}".format(epoch, cost.item()))

epoch: 0, cost: 1.248351
epoch: 300, cost: 0.092303
epoch: 600, cost: 0.036317
epoch: 900, cost: 0.019513
epoch: 1200, cost: 0.012187
epoch: 1500, cost: 0.008305
epoch: 1800, cost: 0.005986
epoch: 2100, cost: 0.004485
epoch: 2400, cost: 0.003455
epoch: 2700, cost: 0.002719
epoch: 3000, cost: 0.002175


In [17]:
import numpy as np
from sklearn.linear_model import LogisticRegression

x_train = np.array([[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5],[1,2,5,6],[1,6,6,6],[1,7,7,7]])
y_train = np.array([2,2,2,1,1,1,0,0])
logistic = LogisticRegression(penalty='none')
logistic.fit(x_train, y_train)
pred = logistic.predict([[1,11,10,9],[1,3,4,3],[1,1,0,1]])
print(pred)

[0 1 2]


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:1173: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
