In [1]:
import torch

In [2]:
x = torch.tensor([[1,2,3,], [4,5,6], [7,8,9]])
y = torch.FloatTensor([[1,2,3], [4,5,6], [7,8,9]])
print("x =", x)
print("y =", y)

x = tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
y = tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [3]:
print("Size:", x.size())
print("Shape:", x.size())
print("차원(랭크):", x.ndimension())

Size: torch.Size([3, 3])
Shape: torch.Size([3, 3])
차원(랭크): 2


In [4]:
x0 = torch.unsqueeze(x,0)
x1 = torch.unsqueeze(x,1)
x2 = torch.unsqueeze(x,2)
print("x0.shape:", x0.shape)
print("x1.shape:", x1.shape)
print("x2.shape:", x2.shape)
print("x0 =", x0)
print("x1 =", x1)
print("x2 =", x2)

x0.shape: torch.Size([1, 3, 3])
x1.shape: torch.Size([3, 1, 3])
x2.shape: torch.Size([3, 3, 1])
x0 = tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
x1 = tensor([[[1, 2, 3]],

        [[4, 5, 6]],

        [[7, 8, 9]]])
x2 = tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]],

        [[7],
         [8],
         [9]]])


In [5]:
x3 = torch.squeeze(torch.squeeze(x0))
print("x3 =", x3)
print("x3.shape =", x3.shape)

x3 = tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
x3.shape = torch.Size([3, 3])


In [6]:
x4 = x.view(9)
x5 = x.view(1,3,3)
print("x4 =", x4)
print("x5 =", x5)

x4 = tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
x5 = tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [7]:
x = torch.FloatTensor([[1,2],[3,4],[5,6]])
w = torch.randn(1,2, dtype=torch.float)
b = torch.randn(3,1, dtype=torch.float)
result = torch.mm(x, torch.t(w))+b
print(result)

tensor([[-2.8106],
        [-4.6912],
        [-6.2471]])


In [8]:
w = torch.tensor(1.0, requires_grad=True)
a = w*3
l = a**2
l.backward()
print('1을 w로 미분한 값은', w.grad)

1을 w로 미분한 값은 tensor(18.)


In [9]:
x_train = torch.FloatTensor([[1,2],[3,2],[3,7],[1,1],[1,0]])
y_train = torch.FloatTensor([[4],[8],[23],[1],[-2]])

In [10]:
W = torch.rand(2,1)
b = torch.rand(1,1)
lr = 0.01
for epoch in range(3001):
  W.requires_grad_(True)
  b.requires_grad_(True)
  h = torch.mm(x_train, W)+b
  cost = torch.mean((h-y_train)**2)
  cost.backward()
  with torch.no_grad():
    W = W - lr * W.grad
    b = b - lr * b.grad
    if epoch % 100 == 0:
      print('epoch: {}, cost: {:.6f}, W: {}, b; {}'.format(epoch, cost.item(), W.squeeze(), b))

epoch: 0, cost: 90.819237, W: tensor([0.6866, 0.7987]), b; tensor([[0.7182]])
epoch: 100, cost: 1.818705, W: tensor([0.5326, 3.1561]), b; tensor([[-1.1303]])
epoch: 200, cost: 0.889254, W: tensor([0.8271, 3.1999]), b; tensor([[-2.0264]])
epoch: 300, cost: 0.456421, W: tensor([1.1455, 3.1533]), b; tensor([[-2.5946]])
epoch: 400, cost: 0.234556, W: tensor([1.3859, 3.1110]), b; tensor([[-2.9936]])
epoch: 500, cost: 0.120543, W: tensor([1.5596, 3.0797]), b; tensor([[-3.2786]])
epoch: 600, cost: 0.061949, W: tensor([1.6842, 3.0572]), b; tensor([[-3.4829]])
epoch: 700, cost: 0.031837, W: tensor([1.7736, 3.0410]), b; tensor([[-3.6293]])
epoch: 800, cost: 0.016361, W: tensor([1.8377, 3.0294]), b; tensor([[-3.7342]])
epoch: 900, cost: 0.008408, W: tensor([1.8837, 3.0211]), b; tensor([[-3.8095]])
epoch: 1000, cost: 0.004321, W: tensor([1.9166, 3.0151]), b; tensor([[-3.8634]])
epoch: 1100, cost: 0.002221, W: tensor([1.9402, 3.0108]), b; tensor([[-3.9021]])
epoch: 1200, cost: 0.001141, W: tensor([

In [11]:
x_test = torch.FloatTensor([[5,10]])
test_result = torch.mm(x_test, W)+b
print(test_result.item())

35.99983215332031


In [12]:
from sklearn.linear_model import LinearRegression
x = [[1,2],[3,2],[3,7],[1,1],[1,0]]
y = [[4],[8],[23],[1],[-2]]
lr = LinearRegression()
lr.fit(x,y)
print(lr.coef_, lr.intercept_)

[[2. 3.]] [-4.]


In [13]:
print(lr.predict([[5,10]]))

[[36.]]


In [14]:
from sklearn.linear_model import LinearRegression
x = [[1,2],[3,2],[3,7],[1,1],[1,0]]
y = [[4],[8],[23],[1],[-2]]

lr = LinearRegression()
lr.fit(x,y)
print(lr.coef_, lr.intercept_)
print(lr.predict([[5,10]]))

[[2. 3.]] [-4.]
[[36.]]
